version: '3.8'
services:
  app:
    image: my-app
    container_name: my-app
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Replace with your app's port
    networks:
      - app-network
    environment:
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=65000
    depends_on:
      - logstash
    volumes:
      - ./logs:/app/logs

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disable security for simplicity (only for local setup)
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app-network
    volumes:
      - es_data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.1
    container_name: logstash
    ports:
      - "65000:65000"
    networks:
      - app-network
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - app-network
    depends_on:
      - elasticsearch

networks:
  app-network:
    driver: bridge
volumes:
  es_data:
